package goemit

// Shared prototype methods are only used at dynamic call boundaries. Statically
// lowered dense-array operations continue to call native storage helpers.
const arrayPrototypeRuntime = `
func tsToLength(loop *tsLoop,value tsValue)int{number:=tsNumber(tsToPrimitive(value));if math.IsNaN(number)||number<=0{return 0};if number>9007199254740991{number=9007199254740991};return int(math.Floor(number))}
func tsArrayPropertyEnumerable(loop *tsLoop,value tsValue,key tsValue)bool{if value.kind==tsStringKind{name:=tsPropertyKey(key);index,err:=strconv.Atoi(name);return err==nil&&strconv.Itoa(index)==name&&index>=0&&index<len((*tsString)(value.ref).units)};if tsIsPrimitiveValue(value){if tsNullish(value){tsPropertyFailure("Cannot reflect null or undefined")};return false};description:=tsOwnDescriptor(loop,value,tsPropertyKey(key));return !tsIsUndefined(description)&&tsTruthy(tsGet(description,"enumerable"))}
func tsArrayPrototype(loop *tsLoop)tsValue{tsEnsureBuiltinClasses(loop);class:=tsBuiltinClasses["Array"];class.prototypeOnce.Do(func(){
 array:=&tsArray{prototype:tsObjectPrototype(),properties:map[string]tsValue{},descriptors:map[string]*tsDescriptor{}};class.prototypeValue=tsArrayValue(array)
 install:=func(name string,length int,method func(*tsLoop,tsValue,...tsValue)tsValue){array.properties[name]=tsNamedNativeMethod(name,length,method);array.order=append(array.order,name);array.descriptors[name]=&tsDescriptor{writable:true,configurable:true}}
 array.properties["constructor"]=tsClassValue(class);array.order=append(array.order,"constructor");array.descriptors["constructor"]=&tsDescriptor{writable:true,configurable:true}
 install("push",1,func(loop *tsLoop,receiver tsValue,args ...tsValue)tsValue{if tsNullish(receiver){tsPropertyFailure("Array.push requires a receiver")};if receiver.kind==tsArrayKind{array:=(*tsArray)(receiver.ref);array.appendItems(loop,args...);return tsNumberValue(float64(array.length()))};length:=tsToLength(tsGet(receiver,"length"));if float64(length)+float64(len(args))>9007199254740991{tsPropertyFailure("Array-like length exceeds the safe integer range")};for i,value:=range args{tsSet(receiver,tsStringReference(tsStringUTF8(strconv.Itoa(length+i))),value)};tsSet(receiver,"length",tsNumberValue(float64(length+len(args))));return tsNumberValue(float64(length+len(args)))})
 install("join",1,func(loop *tsLoop,receiver tsValue,args ...tsValue)tsValue{if tsNullish(receiver){tsPropertyFailure("Array.join requires a receiver")};if receiver.kind==tsArrayKind||receiver.kind==tsTypedArrayKind{return tsCall(loop,tsSequenceMethod(receiver,"join"),args...)};length:=tsToLength(tsGet(receiver,"length"));separator:=tsStringUTF8(",");if !tsIsUndefined(tsArg(args,0)){separator=tsStringValue(args[0])};text:=tsStringUnits(nil);for i:=0;i<length;i++{if i!=0{text=tsStringConcat(text,separator)};value:=tsGet(receiver,tsStringReference(tsStringUTF8(strconv.Itoa(i))));if !tsNullish(value){text=tsStringConcat(text,tsStringValue(value))}};return tsStringReference(text)})
 for _,entry:=range []struct{name string;length int}{{"at",1},{"concat",1},{"copyWithin",2},{"entries",0},{"every",1},{"fill",1},{"filter",1},{"find",1},{"findIndex",1},{"findLast",1},{"findLastIndex",1},{"flat",0},{"flatMap",1},{"forEach",1},{"includes",1},{"indexOf",1},{"keys",0},{"lastIndexOf",1},{"map",1},{"pop",0},{"reduce",1},{"reduceRight",1},{"reverse",0},{"shift",0},{"slice",2},{"some",1},{"sort",1},{"splice",2},{"toReversed",0},{"toSorted",1},{"toSpliced",2},{"unshift",1},{"values",0},{"with",2}}{name:=entry.name;install(name,entry.length,func(loop *tsLoop,receiver tsValue,args ...tsValue)tsValue{if receiver.kind!=tsArrayKind&&receiver.kind!=tsTypedArrayKind{tsPropertyFailure("Generic array receiver is not supported for this method")};return tsCall(loop,tsSequenceMethod(receiver,name),args...)})}
 install("toString",0,func(loop *tsLoop,receiver tsValue,args ...tsValue)tsValue{method:=tsGet(receiver,"join");if method.kind==tsFunctionKind{return tsCallReceiver(loop,method,receiver)};return tsObjectTag(loop,receiver)})
 key:=tsPropertyKey(tsWellKnownSymbol("iterator"));array.properties[key]=array.properties["values"];array.order=append(array.order,key);array.descriptors[key]=&tsDescriptor{writable:true,configurable:true}
 });return class.prototypeValue}
func tsInitArrayStatics(loop *tsLoop,class *tsClass){class.staticOnce.Do(func(){properties:=tsInstanceProperties(class.static);if properties.accessors==nil{properties.accessors=map[string]*tsDescriptor{}};for _,name:=range []string{"isArray","from","of"}{operation:=name;length:=1;if name=="of"{length=0};properties.define(name);properties.extra[name]=tsNamedNativeMethod(name,length,func(loop *tsLoop,receiver tsValue,args ...tsValue)tsValue{return tsArrayBuiltin(operation,args)});properties.accessors[name]=&tsDescriptor{writable:true,configurable:true}}})}
`
