package goemit

const ArrayRuntime = `
func tsArrayTypeFailure(message string){panic(tsThrown{tsErrorValue(&tsRuntimeError{"TypeError",message})})}
func tsArrayRangeFailure(message string){panic(tsThrown{tsErrorValue(&tsRuntimeError{"RangeError",message})})}
type tsNativeNumber interface{tsNativeInteger|float32|float64}
type tsTypedArray struct {storage unsafe.Pointer;buffer *tsArrayBuffer;offset int;length,bytes int;name string;read func(int)float64;write func(int,float64);view func(int,int)*tsTypedArray;order []string;properties map[string]tsValue}
func tsTypedArrayValue(array *tsTypedArray)tsValue{return tsValue{kind:tsTypedArrayKind,ref:unsafe.Pointer(array)}}
func tsNativeArray[T tsNativeNumber](data []T,name string,convert func(float64)T)*tsTypedArray{storage:=&tsNativeArrayStorage[T]{values:data};array:=&tsTypedArray{storage:unsafe.Pointer(storage),length:len(data),bytes:int(unsafe.Sizeof(*new(T))),name:name};array.buffer=&tsArrayBuffer{data:unsafe.Slice((*byte)(unsafe.Pointer(unsafe.SliceData(data))),len(data)*array.bytes)};array.read=func(i int)float64{return float64(data[i])};array.write=func(i int,n float64){data[i]=convert(n)};array.view=func(start,end int)*tsTypedArray{view:=tsNativeArray(data[start:end],name,convert);view.buffer=array.buffer;view.offset=array.offset+start*array.bytes;return view};return array}
func tsNewTypedArray(name string,args ...tsValue)tsValue{source:=tsArg(args,0);if source.kind==tsArrayBufferKind{return tsTypedArrayBuffer(name,args)};values:=[]float64{};length:=0;if tsIsPrimitiveValue(source)&&!tsNullish(source){n:=tsNumber(source);if math.IsNaN(n){n=0};n=math.Trunc(n);if n<0||math.IsInf(n,0)||n>1073741824{tsArrayRangeFailure("Invalid typed array length")};length=int(n)}else if !tsNullish(source){it:=tsArrayLikeIterator(source);for it.next(){values=append(values,tsNumber(tsToPrimitive(it.value)))};length=len(values)};var array *tsTypedArray;switch name{case "Float64Array":array=tsNativeArray(make([]float64,length),name,func(n float64)float64{return n});case "Float32Array":array=tsNativeArray(make([]float32,length),name,func(n float64)float32{return float32(n)});case "Int8Array":array=tsNativeArray(make([]int8,length),name,func(n float64)int8{return int8(tsNumberUint32(n))});case "Uint8Array":array=tsNativeArray(make([]uint8,length),name,func(n float64)uint8{return uint8(tsNumberUint32(n))});case "Uint8ClampedArray":array=tsNativeArray(make([]uint8,length),name,func(n float64)uint8{if math.IsNaN(n)||n<=0{return 0};if n>=255{return 255};return uint8(math.RoundToEven(n))});case "Int16Array":array=tsNativeArray(make([]int16,length),name,func(n float64)int16{return int16(tsNumberUint32(n))});case "Uint16Array":array=tsNativeArray(make([]uint16,length),name,func(n float64)uint16{return uint16(tsNumberUint32(n))});case "Int32Array":array=tsNativeArray(make([]int32,length),name,func(n float64)int32{return int32(tsNumberUint32(n))});case "Uint32Array":array=tsNativeArray(make([]uint32,length),name,func(n float64)uint32{return tsNumberUint32(n)});default:panic("Unsupported typed array constructor")};for i,n:=range values{array.write(i,n)};return tsTypedArrayValue(array)}
func tsTypedArrayGet(value tsValue,name string)tsValue{array:=(*tsTypedArray)(value.ref);switch name{case "buffer":return tsArrayBufferValue(array.buffer);case "byteOffset":return tsNumberValue(float64(array.offset));case "length":return tsNumberValue(float64(array.length));case "byteLength":return tsNumberValue(float64(array.length*array.bytes));case "BYTES_PER_ELEMENT":return tsNumberValue(float64(array.bytes));case "subarray","slice":return tsFunc(func(args ...tsValue)tsValue{start:=tsArrayBound(tsArg(args,0),array.length,0);end:=tsArrayBound(tsArg(args,1),array.length,array.length);if end<start{end=start};view:=tsTypedArrayValue(array.view(start,end));if name=="slice"{return tsNewTypedArray(array.name,view)};return view});case "set":return tsFunc(func(args ...tsValue)tsValue{offset:=tsArrayBound(tsArg(args,1),array.length,0);if !tsIsUndefined(tsArg(args,1))&&(tsNumber(tsArg(args,1))<0||tsNumber(tsArg(args,1))>float64(array.length)){tsArrayRangeFailure("Invalid typed array offset")};it:=tsArrayLikeIterator(tsArg(args,0));items:=[]float64{};for it.next(){items=append(items,tsNumber(tsToPrimitive(it.value)))};if len(items)>array.length-offset{tsArrayRangeFailure("Typed array source is too large")};for i,item:=range items{array.write(offset+i,item)};return tsU})};if item,ok:=array.properties[name];ok{return item};if i,err:=strconv.Atoi(name);err==nil&&strconv.Itoa(i)==name{if i>=0&&i<array.length{return tsNumberValue(array.read(i))};return tsU};if tsCanonicalNumericKey(name){return tsU};return tsSequenceMethod(value,name)}
func tsTypedArraySet(value,key,item tsValue)tsValue{array:=(*tsTypedArray)(value.ref);name:=tsPropertyKey(key);if i,err:=strconv.Atoi(name);err==nil&&strconv.Itoa(i)==name{n:=tsNumber(tsToPrimitive(item));if i>=0&&i<array.length{array.write(i,n)};return item};if tsCanonicalNumericKey(name){tsNumber(tsToPrimitive(item));return item};if name=="length"||name=="byteLength"||name=="BYTES_PER_ELEMENT"||name=="buffer"||name=="byteOffset"{tsArrayTypeFailure("Typed array length is read-only")};if array.properties==nil{array.properties=map[string]tsValue{}};if _,ok:=array.properties[name];!ok{array.order=append(array.order,name)};array.properties[name]=item;return item}
func tsSequenceLength(value tsValue)int{if value.kind==tsTypedArrayKind{return (*tsTypedArray)(value.ref).length};return (*tsArray)(value.ref).length()}
func tsSequenceItem(value tsValue,i int)tsValue{if value.kind==tsTypedArrayKind{return tsNumberValue((*tsTypedArray)(value.ref).read(i))};return (*tsArray)(value.ref).at(i)}
func tsSequencePresent(value tsValue,i int)bool{return value.kind==tsTypedArrayKind||!(*tsArray)(value.ref).holes[i]}
func tsArrayBound(value tsValue,length,fallback int)int{if tsIsUndefined(value){return fallback};n:=math.Trunc(tsNumber(tsToPrimitive(value)));if math.IsNaN(n){return 0};if n<0{n+=float64(length)};if n<0{return 0};if n>float64(length){return length};return int(n)}
func tsSameValueZero(a,b tsValue)bool{return tsStrictEqual(a,b)||(tsIsNumeric(a)&&tsIsNumeric(b)&&math.IsNaN(tsNumber(a))&&math.IsNaN(tsNumber(b)))}
func tsSequenceMethod(value tsValue,name string)tsValue{switch name{case "flat","flatMap","with","toSpliced","copyWithin","toReversed","toSorted","at","join","slice","concat","map","filter","forEach","every","some","find","findIndex","findLast","findLastIndex","reduce","reduceRight","includes","indexOf","lastIndexOf","fill","reverse","sort","keys","values","entries","pop","shift","unshift","splice":default:return tsU};if value.kind==tsTypedArrayKind&&(name=="pop"||name=="shift"||name=="unshift"||name=="splice"||name=="concat"||name=="flat"||name=="flatMap"||name=="toSpliced"){return tsU};return tsFunc(func(args ...tsValue)tsValue{length:=tsSequenceLength(value);arg:=tsArg(args,0);out:=&tsArray{};switch name{
 case "keys","values","entries":i:=0;done:=false;return tsIteratorValueReference(&tsIterator{pull:func()(tsValue,bool){if done||i>=tsSequenceLength(value){done=true;return tsU,false};index:=i;i++;key:=tsNumberValue(float64(index));if name=="keys"{return key,true};item:=tsSequenceItem(value,index);if name=="entries"{return tsArrayValue(&tsArray{values:[]tsValue{key,item}}),true};return item,true}})
 case "flat","flatMap":depth:=float64(1);mapper:=tsU;if name=="flatMap"{mapper=arg;if mapper.kind!=tsFunctionKind{tsArrayTypeFailure("Callback must be callable")}}else if !tsIsUndefined(arg){depth=math.Trunc(tsNumber(tsToPrimitive(arg)));if math.IsNaN(depth)||depth<0{depth=0}};tsArrayFlatten(out,value,depth,mapper,0);return tsArrayValue(out)
 case "with":index:=math.Trunc(tsNumber(tsToPrimitive(arg)));if math.IsNaN(index){index=0};if index<0{index+=float64(length)};replacement:=tsArg(args,1);if value.kind==tsTypedArrayKind{replacement=tsNumberValue(tsNumber(tsToPrimitive(replacement)))};if index<0||index>=float64(length){tsArrayRangeFailure("Array replacement index out of range")};for i:=0;i<length;i++{item:=tsSequenceItem(value,i);if i==int(index){item=replacement};out.values=append(out.values,item)};if value.kind==tsTypedArrayKind{return tsNewTypedArray((*tsTypedArray)(value.ref).name,tsArrayValue(out))};return tsArrayValue(out)
 case "toSpliced":for i:=0;i<length;i++{out.values=append(out.values,tsSequenceItem(value,i))};tsArrayMutate(out,"splice",args);return tsArrayValue(out)
 case "copyWithin":target:=tsArrayBound(arg,length,0);start:=tsArrayBound(tsArg(args,1),length,0);end:=tsArrayBound(tsArg(args,2),length,length);count:=end-start;if count>length-target{count=length-target};if count<=0{return value};if value.kind==tsTypedArrayKind{array:=(*tsTypedArray)(value.ref);copy(array.buffer.data[array.offset+target*array.bytes:array.offset+(target+count)*array.bytes],array.buffer.data[array.offset+start*array.bytes:array.offset+(start+count)*array.bytes])}else{array:=(*tsArray)(value.ref);holes:=make([]bool,count);for i:=range holes{holes[i]=array.holes[start+i]};items:=make([]tsValue,count);for i:=range items{items[i]=array.at(start+i)};for i,item:=range items{if !holes[i]{array.put(target+i,item)}};for i,hole:=range holes{delete(array.holes,target+i);if hole{tsArrayMarkHole(array,target+i)}}};return value
 case "toReversed","toSorted":for i:=0;i<length;i++{out.values=append(out.values,tsSequenceItem(value,i))};copy:=tsArrayValue(out);if value.kind==tsTypedArrayKind{copy=tsNewTypedArray((*tsTypedArray)(value.ref).name,copy)};method:="reverse";if name=="toSorted"{method="sort"};return tsCall(tsSequenceMethod(copy,method),args...)
 case "at":n:=math.Trunc(tsNumber(tsToPrimitive(arg)));if n<0{n+=float64(length)};if math.IsNaN(n){n=0};if n<0||n>=float64(length){return tsU};return tsSequenceItem(value,int(n))
 case "join":separator:=tsStringUTF8(",");if !tsIsUndefined(arg){separator=tsStringValue(arg)};result:=tsStringUnits(nil);for i:=0;i<length;i++{if i>0{result=tsStringConcat(result,separator)};item:=tsSequenceItem(value,i);if !tsNullish(item){result=tsStringConcat(result,tsStringValue(item))}};return tsStringReference(result)
 case "slice":start:=tsArrayBound(arg,length,0);end:=tsArrayBound(tsArg(args,1),length,length);for i:=start;i<end;i++{if tsSequencePresent(value,i){out.values=append(out.values,tsSequenceItem(value,i))}else{tsArrayHole(out)}};return tsArrayValue(out)
 case "concat":sources:=append([]tsValue{value},args...);for _,source:=range sources{if source.kind==tsArrayKind{for i:=0;i<tsSequenceLength(source);i++{if tsSequencePresent(source,i){out.values=append(out.values,tsSequenceItem(source,i))}else{tsArrayHole(out)}}}else{out.values=append(out.values,source)}};return tsArrayValue(out)
 case "includes","indexOf","lastIndexOf":start:=tsArrayBound(tsArg(args,1),length,0);step:=1;if name=="lastIndexOf"{start=length-1;if len(args)>1{n:=math.Trunc(tsNumber(tsToPrimitive(args[1])));if n<0{n+=float64(length)};if math.IsNaN(n){n=0};if n<0{return tsNumberValue(-1)};if n<float64(length){start=int(n)}};step=-1};for i:=start;i>=0&&i<length;i+=step{if name!="includes"&&!tsSequencePresent(value,i){continue};item:=tsSequenceItem(value,i);match:=tsStrictEqual(item,arg);if name=="includes"{match=tsSameValueZero(item,arg)};if match{if name=="includes"{return tsBooleanValue(true)};return tsNumberValue(float64(i))}};if name=="includes"{return tsBooleanValue(false)};return tsNumberValue(-1)
 case "fill":if value.kind==tsTypedArrayKind{arg=tsNumberValue(tsNumber(tsToPrimitive(arg)))};start:=tsArrayBound(tsArg(args,1),length,0);end:=tsArrayBound(tsArg(args,2),length,length);for i:=start;i<end;i++{tsSet(value,tsNumberValue(float64(i)),arg)};return value
 case "reverse":for i,j:=0,length-1;i<j;i,j=i+1,j-1{a,b:=tsSequenceItem(value,i),tsSequenceItem(value,j);pa,pb:=tsSequencePresent(value,i),tsSequencePresent(value,j);if pb{tsSet(value,tsNumberValue(float64(i)),b)};if pa{tsSet(value,tsNumberValue(float64(j)),a)};if value.kind==tsArrayKind{array:=(*tsArray)(value.ref);if !pb{tsArrayMarkHole(array,i)};if !pa{tsArrayMarkHole(array,j)}}};return value
 case "sort":if !tsIsUndefined(arg)&&arg.kind!=tsFunctionKind{tsArrayTypeFailure("Comparator must be callable")};items:=[]tsValue{};undefined,holes:=0,0;for i:=0;i<length;i++{if !tsSequencePresent(value,i){holes++;continue};item:=tsSequenceItem(value,i);if tsIsUndefined(item){undefined++}else{items=append(items,item)}};sort.SliceStable(items,func(i,j int)bool{if arg.kind==tsFunctionKind{return tsNumber(tsCall(arg,items[i],items[j]))<0};if value.kind==tsTypedArrayKind{a,b:=tsNumber(items[i]),tsNumber(items[j]);if math.IsNaN(b){return !math.IsNaN(a)};if a==0&&b==0{return math.Signbit(a)&&!math.Signbit(b)};return a<b};return tsStringCompare(tsStringValue(items[i]),tsStringValue(items[j]))<0});for i,item:=range items{tsSet(value,tsNumberValue(float64(i)),item)};for i:=len(items);i<length-holes;i++{tsSet(value,tsNumberValue(float64(i)),tsU)};if value.kind==tsArrayKind{for i:=length-holes;i<length;i++{tsArrayMarkHole((*tsArray)(value.ref),i)}};_ = undefined;return value
 case "pop","shift","unshift","splice":return tsArrayMutate((*tsArray)(value.ref),name,args)
 case "reduce","reduceRight":if arg.kind!=tsFunctionKind{tsArrayTypeFailure("Callback must be callable")};i,step:=0,1;if name=="reduceRight"{i,step=length-1,-1};acc:=tsArg(args,1);has:=len(args)>1;for ;i>=0&&i<length;i+=step{if !tsSequencePresent(value,i){continue};item:=tsSequenceItem(value,i);if !has{acc=item;has=true}else{acc=tsCall(arg,acc,item,tsNumberValue(float64(i)),value)}};if !has{tsArrayTypeFailure("Reduce of empty array without initial value")};return acc
 default:if arg.kind!=tsFunctionKind{tsArrayTypeFailure("Callback must be callable")};start,step:=0,1;if name=="findLast"||name=="findLastIndex"{start,step=length-1,-1};for i:=start;i>=0&&i<length;i+=step{find:=name=="find"||name=="findIndex"||name=="findLast"||name=="findLastIndex";if i>=tsSequenceLength(value){if !find{if name=="map"{tsArrayHole(out)};continue}}else if !find&&!tsSequencePresent(value,i){if name=="map"{tsArrayHole(out)};continue};item:=tsU;if i<tsSequenceLength(value){item=tsSequenceItem(value,i)};result:=tsCall(arg,item,tsNumberValue(float64(i)),value);switch name{case "map":out.values=append(out.values,result);case "filter":if tsTruthy(result){out.values=append(out.values,item)};case "every":if !tsTruthy(result){return tsBooleanValue(false)};case "some":if tsTruthy(result){return tsBooleanValue(true)};case "find","findLast":if tsTruthy(result){return item};case "findIndex","findLastIndex":if tsTruthy(result){return tsNumberValue(float64(i))}}};switch name{case "forEach","find","findLast":return tsU;case "every":return tsBooleanValue(true);case "some":return tsBooleanValue(false);case "findIndex","findLastIndex":return tsNumberValue(-1)};if value.kind==tsTypedArrayKind{return tsNewTypedArray((*tsTypedArray)(value.ref).name,tsArrayValue(out))};return tsArrayValue(out)
 }})}
func tsArrayMarkHole(array *tsArray,index int){if array.native!=nil{tsArrayRangeFailure("Primitive arrays cannot contain holes")};if array.holes==nil{array.holes=map[int]bool{}};array.holes[index]=true;array.clearSlot(index)}

func tsArrayMutate(array *tsArray,name string,args []tsValue)tsValue{length:=array.length();if name=="pop"{if length==0{return tsU};item:=array.at(length-1);array.resize(length-1);delete(array.holes,length-1);return item};start,remove:=0,0;insert:=args;if name=="shift"{remove=1;if length==0{return tsU};insert=nil}else if name=="splice"{start=tsArrayBound(tsArg(args,0),length,0);remove=length-start;if len(args)==0{remove=0};if len(args)>1{n:=math.Trunc(tsNumber(tsToPrimitive(args[1])));if math.IsNaN(n)||n<0{n=0};if n<float64(remove){remove=int(n)}};insert=nil;if len(args)>2{insert=args[2:]}};out:=&tsArray{};for i:=start;i<start+remove;i++{if array.holes[i]{tsArrayHole(out)}else{out.values=append(out.values,array.at(i))}};holes:=map[int]bool{};for index:=range array.holes{if index<start{holes[index]=true}else if index>=start+remove{holes[index-remove+len(insert)]=true}};if array.growSplice!=nil{array.growSplice(start,remove,insert)}else{converted:=append([]tsValue{},insert...);if array.elementKind!=""{for i,item:=range converted{converted[i]=tsBoundary(item,array.elementKind,array.elementNulls,array.elementCoerce)}};values:=make([]tsValue,0,length-remove+len(insert));values=append(values,array.values[:start]...);values=append(values,converted...);values=append(values,array.values[start+remove:]...);array.values=values};array.holes=holes;if name=="shift"{return out.at(0)};if name=="unshift"{return tsNumberValue(float64(array.length()))};return tsArrayValue(out)}

`

const ArrayBuiltinRuntime = `
var tsBuiltinClasses=tsMakeBuiltinClasses()
func tsMakeBuiltinClasses()map[string]*tsClass{out:=map[string]*tsClass{};for _,name:=range []string{"Map","Set","Array","ArrayBuffer","Float64Array","Float32Array","Int8Array","Uint8Array","Uint8ClampedArray","Int16Array","Uint16Array","Int32Array","Uint32Array"}{class:=&tsClass{builtin:name,static:tsInstanceValue(tsNewProperties())};class.construct=func(loop *tsLoop,args ...tsValue)tsValue{switch name{case "Map","Set":return tsNewCollection(name=="Set",args...);case "Array":return tsNewArray(args...);case "ArrayBuffer":return tsNewArrayBuffer(args...);default:return tsNewTypedArray(name,args...)}};out[name]=class};return out}
func tsBuiltinClass(name string)tsValue{return tsClassValue(tsBuiltinClasses[name])}
func tsCanonicalNumericKey(name string)bool{if name=="-0"{return true};n,err:=strconv.ParseFloat(name,64);return err==nil&&tsNumberText(n)==name}
func tsArrayBuiltin(name string,args []tsValue)tsValue{switch name{case "isArray":return tsBooleanValue(tsArg(args,0).kind==tsArrayKind);case "of":return tsArrayValue(&tsArray{values:append([]tsValue{},args...)});case "from":source:=tsArg(args,0);out:=&tsArray{};mapper:=tsArg(args,1);if !tsIsUndefined(mapper)&&mapper.kind!=tsFunctionKind{panic("Array.from mapper must be callable")};it:=tsArrayLikeIterator(source);for it.next(){item:=it.value;if mapper.kind==tsFunctionKind{item=tsCall(mapper,item,tsNumberValue(float64(len(out.values))))};out.values=append(out.values,item)};return tsArrayValue(out)};panic("Unsupported Array builtin")}
func tsNewArray(args ...tsValue)tsValue{array:=&tsArray{};if len(args)==1&&tsIsNumeric(args[0]){n:=tsNumber(args[0]);if n<0||math.IsInf(n,0)||math.IsNaN(n)||n>4294967295||math.Trunc(n)!=n{tsArrayRangeFailure("Invalid array length")};for len(array.values)<int(n){tsArrayHole(array)}}else{array.values=append(array.values,args...)};return tsArrayValue(array)}
`

const BufferRuntime = `
type tsArrayBuffer struct {data []byte}
func tsArrayBufferValue(buffer *tsArrayBuffer)tsValue{return tsValue{kind:tsArrayBufferKind,ref:unsafe.Pointer(buffer)}}
func tsToIndex(value tsValue)int{if tsIsUndefined(value){return 0};n:=math.Trunc(tsNumber(tsToPrimitive(value)));if math.IsNaN(n){n=0};if n<0||math.IsInf(n,0)||n>1073741824{tsArrayRangeFailure("Invalid buffer index")};return int(n)}
func tsNewArrayBuffer(args ...tsValue)tsValue{return tsArrayBufferValue(&tsArrayBuffer{data:make([]byte,tsToIndex(tsArg(args,0)))})}
func tsTypedArrayWidth(name string)int{switch name{case "Float64Array":return 8;case "Float32Array","Int32Array","Uint32Array":return 4;case "Int16Array","Uint16Array":return 2;default:return 1}}
func tsNativeBufferView[T tsNativeNumber](buffer *tsArrayBuffer,offset,length int,name string,convert func(float64)T)*tsTypedArray{data:=unsafe.Slice((*T)(unsafe.Pointer(unsafe.SliceData(buffer.data[offset:]))),length);array:=tsNativeArray(data,name,convert);array.buffer=buffer;array.offset=offset;return array}
func tsTypedArrayBuffer(name string,args []tsValue)tsValue{buffer:=(*tsArrayBuffer)(args[0].ref);width:=tsTypedArrayWidth(name);offset:=tsToIndex(tsArg(args,1));if offset%width!=0||offset>len(buffer.data){tsArrayRangeFailure("Invalid typed array byte offset")};length:=0;if tsIsUndefined(tsArg(args,2)){if (len(buffer.data)-offset)%width!=0{tsArrayRangeFailure("Invalid typed array buffer length")};length=(len(buffer.data)-offset)/width}else{length=tsToIndex(args[2]);if length>(len(buffer.data)-offset)/width{tsArrayRangeFailure("Typed array exceeds buffer")}};var array *tsTypedArray;switch name{case "Float64Array":array=tsNativeBufferView(buffer,offset,length,name,func(n float64)float64{return n});case "Float32Array":array=tsNativeBufferView(buffer,offset,length,name,func(n float64)float32{return float32(n)});case "Int8Array":array=tsNativeBufferView(buffer,offset,length,name,func(n float64)int8{return int8(tsNumberUint32(n))});case "Uint8Array":array=tsNativeBufferView(buffer,offset,length,name,func(n float64)uint8{return uint8(tsNumberUint32(n))});case "Uint8ClampedArray":array=tsNativeBufferView(buffer,offset,length,name,func(n float64)uint8{if math.IsNaN(n)||n<=0{return 0};if n>=255{return 255};return uint8(math.RoundToEven(n))});case "Int16Array":array=tsNativeBufferView(buffer,offset,length,name,func(n float64)int16{return int16(tsNumberUint32(n))});case "Uint16Array":array=tsNativeBufferView(buffer,offset,length,name,func(n float64)uint16{return uint16(tsNumberUint32(n))});case "Int32Array":array=tsNativeBufferView(buffer,offset,length,name,func(n float64)int32{return int32(tsNumberUint32(n))});case "Uint32Array":array=tsNativeBufferView(buffer,offset,length,name,func(n float64)uint32{return tsNumberUint32(n)})};return tsTypedArrayValue(array)}
func tsArrayBufferGet(value tsValue,name string)tsValue{buffer:=(*tsArrayBuffer)(value.ref);switch name{case "byteLength":return tsNumberValue(float64(len(buffer.data)));case "slice":return tsFunc(func(args ...tsValue)tsValue{start:=tsArrayBound(tsArg(args,0),len(buffer.data),0);end:=tsArrayBound(tsArg(args,1),len(buffer.data),len(buffer.data));if end<start{end=start};return tsArrayBufferValue(&tsArrayBuffer{data:append([]byte{},buffer.data[start:end]...)})})};return tsU}
`

const TypedArrayBuiltinRuntime = `
func tsTypedArrayBuiltin(name,method string,args []tsValue)tsValue{switch method{case "of":return tsNewTypedArray(name,tsArrayValue(&tsArray{values:append([]tsValue{},args...)}));case "from":return tsNewTypedArray(name,tsArrayBuiltin("from",args))};panic("Unsupported typed array builtin")}
`

const ArrayFlattenRuntime = `
func tsArrayFlatten(out *tsArray,source tsValue,depth float64,mapper tsValue,nesting int){if nesting>1024{tsArrayRangeFailure("Array flattening is too deeply nested")};length:=tsSequenceLength(source);for i:=0;i<length;i++{if i>=tsSequenceLength(source)||!tsSequencePresent(source,i){continue};item:=tsSequenceItem(source,i);if mapper.kind==tsFunctionKind{item=tsCall(mapper,item,tsNumberValue(float64(i)),source)};if depth>0&&item.kind==tsArrayKind{tsArrayFlatten(out,item,depth-1,tsU,nesting+1)}else{out.values=append(out.values,item)}}}
`

const ArrayLikeRuntime = `
func tsArrayLikeIterator(value tsValue)*tsIterator{switch value.kind{case tsArrayKind,tsTypedArrayKind,tsStringKind,tsCollectionKind,tsIteratorKind:return tsIterate(value)};if tsNullish(value){tsArrayTypeFailure("Cannot convert null or undefined to an array")};number:=math.Trunc(tsNumber(tsToPrimitive(tsGet(value,tsStringReference(tsStringUTF8("length"))))));if math.IsNaN(number)||number<0{number=0};if number>1073741824{tsArrayRangeFailure("Array-like length is too large")};length:=int(number);index:=0;return &tsIterator{pull:func()(tsValue,bool){if index>=length{return tsU,false};item:=tsGet(value,tsNumberValue(float64(index)));index++;return item,true}}}
`
