package goemit

// Declared property entries are lenses into concrete fields, never copies of
// their values. The same hash table also holds dynamically added properties.
const ClassRuntime = `
type tsClass struct {prototypeValue tsValue;staticOnce sync.Once;baseConstructor tsValue;computedKeys map[string]string;dynamic bool;prototypeOnce sync.Once;prototypeFactory func()*tsObject;nativePrototype *tsObject;builtin string;layout *tsClassLayout;construct func(...tsValue) tsValue;parent *tsClass;static tsValue}
func tsIsConstructor(value tsValue)bool{if value.kind==tsClassKind{return true};if value.kind!=tsFunctionKind{return false};function:=(*tsFunction)(value.ref);if !tsIsUndefined(function.boundTarget){return tsIsConstructor(function.boundTarget)};return function.constructible}
func tsConstruct(class tsValue,args ...tsValue) tsValue {
 if class.kind==tsFunctionKind{function:=(*tsFunction)(class.ref);if !tsIsUndefined(function.boundTarget){values:=append(append([]tsValue{},function.boundArgs...),args...);return tsConstruct(function.boundTarget,values...)};if !function.constructible{tsPropertyFailure("Value is not a constructor")};prototype:=tsFunctionGet(loop,class,"prototype");if tsIsPrimitiveValue(prototype){prototype=tsObjectPrototype()};object:=tsNewObject();object.prototype=prototype;receiver:=tsObjectValue(object);result:=tsCallReceiver(loop,class,receiver,args...);if !tsIsPrimitiveValue(result){return result};return receiver}
 if class.kind!=tsClassKind {tsPropertyFailure("Value is not a constructor")};return (*tsClass)(class.ref).construct(args...)
}
type tsProperty struct {readField func() tsValue;writeField func(tsValue) tsValue;clearField func()}
type tsProperties struct {errorStack *tsNativeErrorStack;nativeError bool;metadata *tsObject;nonExtensible bool;accessors map[string]*tsDescriptor;dynamicPrototype tsValue;self unsafe.Pointer;layout *tsClassLayout;prototype *tsProperties;order []string;own map[string]bool;class *tsClass;initialized bool;declared map[string]tsProperty;extra map[string]tsValue;methods map[string]tsValue}
func tsNewProperties() *tsProperties {return &tsProperties{own:make(map[string]bool),declared:make(map[string]tsProperty),extra:make(map[string]tsValue),methods:make(map[string]tsValue)}}
func(p *tsProperties)define(name string){if !p.own[name]{p.own[name]=true;p.order=append(p.order,name)}}
func(p *tsProperties)get(name string) tsValue {if property,ok:=p.declared[name];ok {return property.readField()};if value,ok:=p.extra[name];ok{return value};if value,ok:=p.methods[name];ok{return value};if p.prototype!=nil {return p.prototype.get(name)};return tsU}
func(p *tsProperties)set(name string,value tsValue) tsValue {if property,ok:=p.declared[name];ok {return property.writeField(value)};p.define(name);p.extra[name]=value;return value}
func tsRequireThis(object tsValue) tsValue {if !tsInstanceProperties(object).initialized {panic("Cannot access this before super constructor")};return object}
func tsInstanceOf(value,class tsValue)bool{if !tsIsPrimitiveValue(class){method:=tsGet(loop,class,tsWellKnownSymbol("hasInstance"));if !tsNullish(method){return tsTruthy(tsCallReceiver(loop,method,class,value))}};return tsOrdinaryInstanceOf(value,class)}
func tsOrdinaryInstanceOf(value,class tsValue) bool {if class.kind==tsFunctionKind{function:=(*tsFunction)(class.ref);if !tsIsUndefined(function.boundTarget){return tsInstanceOf(value,function.boundTarget)};prototype:=tsFunctionGet(loop,class,"prototype");if tsIsPrimitiveValue(prototype){tsPropertyFailure("Constructor prototype is not an object")};return tsPrototypeContains(value,prototype)};if class.kind!=tsClassKind {tsPropertyFailure("Right operand of instanceof is not callable")};constructor:=(*tsClass)(class.ref);if constructor.dynamic{return tsPrototypeContains(value,tsClassPrototype(constructor))};if constructor.builtin!=""&&constructor.nativePrototype!=nil{if constructor.builtin=="Buffer"{return value.kind==tsTypedArrayKind&&(*tsTypedArray)(value.ref).nodeBuffer};return value.kind==tsObjectKind&&(*tsObject)(value.ref).nativeClass==constructor};if constructor.builtin!=""{switch constructor.builtin{case "Map":return value.kind==tsCollectionKind&&!(*tsCollection)(value.ref).set;case "Set":return value.kind==tsCollectionKind&&(*tsCollection)(value.ref).set;case "Array":return value.kind==tsArrayKind;case "ArrayBuffer":return value.kind==tsArrayBufferKind;default:return value.kind==tsTypedArrayKind&&(*tsTypedArray)(value.ref).name==constructor.builtin}};if value.kind!=tsInstanceKind {return false};for at:=(*tsProperties)(value.ref).class;at!=nil;at=at.parent {if at==constructor {return true}};return false}
type tsClassLayout struct {name string}
`
