package goemit

const CollectionRuntime = `
type tsCollectionKey struct {kind tsKind;bits uint64;text string;ref unsafe.Pointer}
type tsCollectionEntry struct {key,value tsValue;live bool}
type tsCollection struct {set bool;index map[tsCollectionKey]int;entries []tsCollectionEntry;order []string;properties map[string]tsValue}
func tsCollectionValue(value *tsCollection)tsValue{return tsValue{kind:tsCollectionKind,ref:unsafe.Pointer(value)}}
func tsCollectionHash(value tsValue)tsCollectionKey{
 if tsIsSigned(value){return tsCollectionKey{kind:tsInt64Kind,bits:math.Float64bits(value.number)}}
 if tsIsUnsigned(value){bits:=math.Float64bits(value.number);kind:=tsInt64Kind;if bits>math.MaxInt64{kind=tsUint64Kind};return tsCollectionKey{kind:kind,bits:bits}}
 if tsIsNumeric(value){n:=tsNumber(value);if math.IsNaN(n){return tsCollectionKey{kind:tsNumberKind,bits:0x7ff8000000000000}};if n>=-9223372036854775808&&n<9223372036854775808&&math.Trunc(n)==n{return tsCollectionKey{kind:tsInt64Kind,bits:uint64(int64(n))}};if n>=9223372036854775808&&n<18446744073709551616&&math.Trunc(n)==n{return tsCollectionKey{kind:tsUint64Kind,bits:uint64(n)}};return tsCollectionKey{kind:tsNumberKind,bits:math.Float64bits(n)}}
 if value.kind==tsStringKind{return tsCollectionKey{kind:value.kind,text:tsPropertyKey(value)}}
 return tsCollectionKey{kind:value.kind,bits:math.Float64bits(value.number),ref:value.ref}
}
func(c *tsCollection)put(key,value tsValue){hash:=tsCollectionHash(key);if i,ok:=c.index[hash];ok{c.entries[i].value=value;return};if key.kind==tsNumberKind&&key.number==0{key.number=0};c.index[hash]=len(c.entries);c.entries=append(c.entries,tsCollectionEntry{key,value,true})}
func tsNewCollection(set bool,args ...tsValue)tsValue{c:=&tsCollection{set:set,index:map[tsCollectionKey]int{}};source:=tsArg(args,0);if !tsNullish(source){it:=tsIterate(source);for it.next(){if set{c.put(it.value,it.value)}else{pair:=it.value;if tsIsPrimitiveValue(pair){panic("Map entry must be an object")};c.put(tsGet(pair,tsNumberValue(0)),tsGet(pair,tsNumberValue(1)))}}};return tsCollectionValue(c)}
func(c *tsCollection)iterator(mode string)*tsIterator{index:=0;done:=false;return &tsIterator{pull:func()(tsValue,bool){if done{return tsU,false};for index<len(c.entries){entry:=c.entries[index];index++;if !entry.live{continue};switch mode{case "keys":return entry.key,true;case "values":if c.set{return entry.key,true};return entry.value,true;default:value:=entry.value;if c.set{value=entry.key};return tsArrayValue(&tsArray{values:[]tsValue{entry.key,value}}),true}};done=true;return tsU,false}}}
func tsCollectionGet(value tsValue,name string)tsValue{c:=(*tsCollection)(value.ref);if item,ok:=c.properties[name];ok{return item};if name=="size"{return tsNumberValue(float64(len(c.index)))};switch name{case "keys","values","entries":return tsFunc(func(args ...tsValue)tsValue{return tsIteratorValueReference(c.iterator(name))});case "get":if c.set{return tsU};return tsFunc(func(args ...tsValue)tsValue{if i,ok:=c.index[tsCollectionHash(tsArg(args,0))];ok{return c.entries[i].value};return tsU});case "has":return tsFunc(func(args ...tsValue)tsValue{_,ok:=c.index[tsCollectionHash(tsArg(args,0))];return tsBooleanValue(ok)});case "set","add":if (name=="add")!=c.set{return tsU};return tsFunc(func(args ...tsValue)tsValue{key:=tsArg(args,0);item:=tsArg(args,1);if c.set{item=key};c.put(key,item);return value});case "delete":return tsFunc(func(args ...tsValue)tsValue{hash:=tsCollectionHash(tsArg(args,0));i,ok:=c.index[hash];if ok{delete(c.index,hash);c.entries[i]=tsCollectionEntry{}};return tsBooleanValue(ok)});case "clear":return tsFunc(func(args ...tsValue)tsValue{clear(c.index);clear(c.entries);return tsU});case "forEach":return tsFunc(func(args ...tsValue)tsValue{callback:=tsArg(args,0);if callback.kind!=tsFunctionKind{panic("Callback must be callable")};for i:=0;i<len(c.entries);i++{entry:=c.entries[i];if entry.live{item:=entry.value;if c.set{item=entry.key};tsCall(callback,item,entry.key,value)}};return tsU})};if c.set{return tsSetMethod(value,name)};return tsU}
func tsIteratorGet(it *tsIterator,name string)tsValue{if name=="next"{return tsFunc(func(args ...tsValue)tsValue{ok:=it.next();out:=tsNewObject();out.set("done",tsBooleanValue(!ok));value:=tsU;if ok{value=it.value};out.set("value",value);return tsObjectValue(out)})};return tsU}
`

const SetRuntime = `
func tsSetMethod(value tsValue,name string)tsValue{switch name{case "union","intersection","difference","symmetricDifference","isSubsetOf","isSupersetOf","isDisjointFrom":default:return tsU};return tsFunc(func(args ...tsValue)tsValue{self:=(*tsCollection)(value.ref);other:=tsArg(args,0);size:=tsNumber(tsToPrimitive(tsGet(other,tsStringReference(tsStringUTF8("size")))));if math.IsNaN(size)||size<0{panic("Invalid set-like size")};size=math.Trunc(size);has:=tsGet(other,tsStringReference(tsStringUTF8("has")));keys:=tsGet(other,tsStringReference(tsStringUTF8("keys")));if has.kind!=tsFunctionKind||keys.kind!=tsFunctionKind{panic("Expected a set-like object")};out:=&tsCollection{set:true,index:map[tsCollectionKey]int{}};copySelf:=func(){for _,entry:=range self.entries{if entry.live{out.put(entry.key,entry.key)}}};remove:=func(key tsValue){hash:=tsCollectionHash(key);if i,ok:=out.index[hash];ok{delete(out.index,hash);out.entries[i]=tsCollectionEntry{}}};contains:=func(key tsValue)bool{return tsTruthy(tsCall(has,key))};switch name{case "union":copySelf();it:=tsIterate(tsCall(keys));for it.next(){out.put(it.value,it.value)};case "intersection":if float64(len(self.index))<=size{for i:=0;i<len(self.entries);i++{entry:=self.entries[i];if entry.live&&contains(entry.key){out.put(entry.key,entry.key)}}}else{it:=tsIterate(tsCall(keys));for it.next(){if _,ok:=self.index[tsCollectionHash(it.value)];ok{out.put(it.value,it.value)}}};case "difference":copySelf();if float64(len(self.index))<=size{for i:=0;i<len(self.entries);i++{entry:=self.entries[i];if entry.live&&contains(entry.key){remove(entry.key)}}}else{it:=tsIterate(tsCall(keys));for it.next(){remove(it.value)}};case "symmetricDifference":copySelf();it:=tsIterate(tsCall(keys));for it.next(){if _,ok:=self.index[tsCollectionHash(it.value)];ok{remove(it.value)}else{out.put(it.value,it.value)}};case "isSubsetOf":if float64(len(self.index))>size{return tsBooleanValue(false)};for i:=0;i<len(self.entries);i++{entry:=self.entries[i];if entry.live&&!contains(entry.key){return tsBooleanValue(false)}};return tsBooleanValue(true);case "isSupersetOf":if float64(len(self.index))<size{return tsBooleanValue(false)};it:=tsIterate(tsCall(keys));for it.next(){if _,ok:=self.index[tsCollectionHash(it.value)];!ok{return tsBooleanValue(false)}};return tsBooleanValue(true);case "isDisjointFrom":if float64(len(self.index))<=size{for i:=0;i<len(self.entries);i++{entry:=self.entries[i];if entry.live&&contains(entry.key){return tsBooleanValue(false)}}}else{it:=tsIterate(tsCall(keys));for it.next(){if _,ok:=self.index[tsCollectionHash(it.value)];ok{return tsBooleanValue(false)}}};return tsBooleanValue(true)};return tsCollectionValue(out)})}
`
