package goemit

// The tag slice costs one byte per slot, without per-record alignment padding.
// Values remain a typed Go slice, so pointer elements are visible to the GC.
const NullableArrayRuntime = `
func tsNullableCheck[T tsPrimitive](value tsOptional[T],mask uint8)tsOptional[T]{if value.tag>2||value.tag!=0&&mask&value.tag==0{tsArrayTypeFailure("Nullish value is not permitted by the array element type")};if value.tag!=0{var zero T;value.value=zero};return value}
func tsNullableAt[T tsPrimitive](storage *tsGrowableStorage[T],index int)tsOptional[T]{if index<0||index>=len(storage.values){return tsOptional[T]{tag:2}};tag:=uint8(0);if storage.owner.elementNulls!=0{tag=storage.tags[index]};return tsOptional[T]{value:storage.values[index],tag:tag}}
func tsNullableRead[T tsPrimitive](storage *tsGrowableStorage[T],index float64)tsOptional[T]{if math.IsNaN(index)||index<0||index>=float64(len(storage.values))||math.Trunc(index)!=index{tsArrayRangeFailure("Dense array index out of bounds")};return tsNullableAt(storage,int(index))}
func tsNullablePush[T tsPrimitive](storage *tsGrowableStorage[T],items ...tsOptional[T])float64{for _,item:=range items{tsNullableCheck(item,storage.owner.elementNulls)};for _,item:=range items{item=tsNullableCheck(item,storage.owner.elementNulls);storage.values=append(storage.values,item.value);storage.tags=append(storage.tags,item.tag)};return float64(len(storage.values))}
func tsNullableWrite[T tsPrimitive](storage *tsGrowableStorage[T],index float64,item tsOptional[T])tsOptional[T]{if math.IsNaN(index)||index<0||index>float64(len(storage.values))||math.Trunc(index)!=index{tsArrayRangeFailure("Dense array writes cannot create holes")};item=tsNullableCheck(item,storage.owner.elementNulls);if int(index)==len(storage.values){tsNullablePush(storage,item)}else{storage.values[int(index)]=item.value;storage.tags[int(index)]=item.tag};return item}
func tsNullablePop[T tsPrimitive](storage *tsGrowableStorage[T],front bool)tsOptional[T]{length:=len(storage.values);if length==0{return tsOptional[T]{tag:2}};index:=length-1;if front{index=0};result:=tsNullableAt(storage,index);if front{copy(storage.values,storage.values[1:]);copy(storage.tags,storage.tags[1:])};clear(storage.values[length-1:]);clear(storage.tags[length-1:]);storage.values=storage.values[:length-1];storage.tags=storage.tags[:length-1];return result}
func tsNullableUnshift[T tsPrimitive](storage *tsGrowableStorage[T],items ...tsOptional[T])float64{old:=len(storage.values);tsNullablePush(storage,items...);copy(storage.values[len(items):],storage.values[:old]);copy(storage.tags[len(items):],storage.tags[:old]);for i,item:=range items{item=tsNullableCheck(item,storage.owner.elementNulls);storage.values[i]=item.value;storage.tags[i]=item.tag};return float64(len(storage.values))}
func tsNullableSplice[T tsPrimitive](storage *tsGrowableStorage[T],kind string,coerce bool,start,remove float64,items ...tsOptional[T])*tsArray{for _,item:=range items{tsNullableCheck(item,storage.owner.elementNulls)};old:=len(storage.values);first:=tsDenseBound(start,old);remove=math.Trunc(remove);if math.IsNaN(remove)||remove<0{remove=0};count:=old-first;if remove<float64(count){count=int(remove)};result:=tsDenseSlice(storage,kind,coerce,float64(first),float64(first+count));length:=old-count+len(items);if length>old{storage.values=append(storage.values,make([]T,length-old)...);storage.tags=append(storage.tags,make([]uint8,length-old)...)};copy(storage.values[first+len(items):],storage.values[first+count:old]);copy(storage.tags[first+len(items):],storage.tags[first+count:old]);if length<old{clear(storage.values[length:]);clear(storage.tags[length:]);storage.values=storage.values[:length];storage.tags=storage.tags[:length]};for i,item:=range items{item=tsNullableCheck(item,storage.owner.elementNulls);storage.values[first+i]=item.value;storage.tags[first+i]=item.tag};return result}
func tsNullableFill[T tsPrimitive](storage *tsGrowableStorage[T],item tsOptional[T],start,end float64){item=tsNullableCheck(item,storage.owner.elementNulls);first,last:=tsDenseBound(start,len(storage.values)),tsDenseBound(end,len(storage.values));for i:=first;i<last;i++{storage.values[i]=item.value;storage.tags[i]=item.tag}}
func tsNullableFromValues[T tsPrimitive](kind string,nulls uint8,coerce bool,items ...tsOptional[T])*tsArray{result:=tsNewGrowableArray(kind,nulls,coerce);tsNullablePush((*tsGrowableStorage[T])(result.native),items...);return result}
func tsNullableNewSized[T tsPrimitive](kind string,nulls uint8,coerce bool,length float64,zero T)*tsArray{if math.IsNaN(length)||length<0||length>4294967295||length>float64(^uint(0)>>1)||math.Trunc(length)!=length{tsArrayRangeFailure("Invalid dense array length")};result:=tsNewGrowableArray(kind,nulls,coerce);storage:=(*tsGrowableStorage[T])(result.native);storage.values=make([]T,int(length));storage.tags=make([]uint8,int(length));var naturalZero T;if zero!=naturalZero{for i:=range storage.values{storage.values[i]=zero}};return result}
func tsNullableNewArray[T tsPrimitive](kind string,nulls uint8,coerce bool,arg tsValue)*tsArray{if !tsIsNumeric(arg){return tsNullableFromValues(kind,nulls,coerce,tsOptionalFrom[T](tsBoundary(arg,kind,nulls,coerce)))};var zero T;if kind=="string"{zero=tsNative[T](tsStringReference(tsStringUTF8("")))};return tsNullableNewSized(kind,nulls,coerce,tsNumber(arg),zero)}

func(c *tsTypedCell[T])initOptional(value tsOptional[T])tsOptional[T]{value=tsNullableCheck(value,c.nulls);c.value=value.value;c.tag=value.tag;c.initialized=true;return value}
`
