package goemit

const ObjectRuntime = propertyRuntime + prototypeRuntime + prototypeMembershipRuntime + jsonRuntime + mathRuntime + errorRuntime + errorStackRuntime + deleteRuntime + argumentsRuntime + generatorRuntime + computedClassRuntime + symbolRuntime + reflectRuntime + receiverRuntime + arrayPrototypeRuntime + `
func tsArrayHole(array *tsArray){if array.native!=nil{tsArrayRangeFailure("Primitive arrays cannot contain holes")};if array.holes==nil{array.holes=map[int]bool{}};index:=array.length();array.resize(index+1);array.holes[index]=true}
type tsObject struct {errorStack *tsNativeErrorStack;nativeError bool;boxedPrimitive tsValue;argumentMap map[string]tsProperty;rawJSON *tsString;nativeDate bool;descriptors map[string]*tsDescriptor;prototype tsValue;nonExtensible bool;webStream *tsWebStream;blob *tsBlob;nativeTime float64;nativeDates map[string]tsValue;nativeClass *tsClass;nativeMode os.FileMode;streamClose func(*tsLoop)*tsPromise;abort *tsAbortState;asyncIterator func()*tsAsyncIterator;values map[string]tsValue;order []string}
func tsNewObject()*tsObject{return &tsObject{values:make(map[string]tsValue)}}
func(o *tsObject)get(name string)tsValue{if value,ok:=o.values[name];ok{return value};if o.nativeClass!=nil&&(o.nativeClass.builtin=="Stats"||o.nativeClass.builtin=="BigIntStats"){switch name{case "atime","mtime","ctime","birthtime":if value,ok:=o.nativeDates[name];ok{return value};milliseconds:=o.values[name+"Ms"].ToNumber();value:=tsFSDateMillis(milliseconds);if o.nativeDates==nil{o.nativeDates=map[string]tsValue{}};o.nativeDates[name]=value;return value}};if o.nativeClass!=nil&&o.nativeClass.nativePrototype!=nil{return o.nativeClass.nativePrototype.get(name)};return tsU}
func(o *tsObject)set(name string,value tsValue)tsValue{if _,ok:=o.values[name];!ok{o.order=append(o.order,name)};o.values[name]=value;return value}
func tsPropertyKey(value tsValue)string {value=tsPrimitiveHint(loop,value,true);if value.kind==tsSymbolKind{return (*tsSymbol)(value.ref).key};text:=tsStringValue(value);var out strings.Builder;for i:=0;i<len(text.units);i++ {c:=text.units[i];if c>=0xd800&&c<=0xdbff&&i+1<len(text.units)&&text.units[i+1]>=0xdc00&&text.units[i+1]<=0xdfff {out.WriteRune(utf16.DecodeRune(rune(c),rune(text.units[i+1])));i++}else if c>=0xd800&&c<=0xdfff {out.Write([]byte{0xed,0x80|byte(c>>6&0x3f),0x80|byte(c&0x3f)})}else {out.WriteRune(rune(c))}};return out.String()}
func tsStringKey(text string)*tsString {units:=[]uint16{};for len(text)>0 {if len(text)>=3&&text[0]==0xed&&text[1]>=0xa0&&text[1]<=0xbf&&text[2]>=0x80&&text[2]<=0xbf {units=append(units,uint16(text[0]&15)<<12|uint16(text[1]&63)<<6|uint16(text[2]&63));text=text[3:];continue};r,size:=utf8.DecodeRuneInString(text);text=text[size:];if r>0xffff {a,b:=utf16.EncodeRune(r);units=append(units,uint16(a),uint16(b))}else {units=append(units,uint16(r))}};return tsStringUnits(units)}
func tsOrderedKeys(keys []string)[]string {indices,other:=[]string{},[]string{};seen:=map[string]bool{};for _,name:=range keys {if seen[name]{continue};seen[name]=true;index,err:=strconv.ParseUint(name,10,32);if err==nil&&index<0xffffffff&&strconv.FormatUint(index,10)==name {indices=append(indices,name)}else {other=append(other,name)}};sort.Slice(indices,func(i,j int)bool{a,_:=strconv.ParseUint(indices[i],10,32);b,_:=strconv.ParseUint(indices[j],10,32);return a<b});return append(indices,other...)}
func tsForInKeys(value tsValue)*tsArray {if tsNullish(value){return &tsArray{}};return tsPrototypeForIn(value)}
func tsObjectKeys(value tsValue)*tsArray{if value.kind==tsErrorKind{return tsObjectKeys(tsObjectValue(tsErrorObject(loop,(*tsRuntimeError)(value.ref))))};keys:=[]string{};switch value.kind{case tsFunctionKind:if object:=(*tsFunction)(value.ref).readProperties();object!=nil{for _,name:=range object.order{if descriptor:=object.descriptors[name];descriptor==nil||descriptor.enumerable{keys=append(keys,name)}}};case tsTypedArrayKind:v:=(*tsTypedArray)(value.ref);for i:=0;i<v.length;i++{keys=append(keys,strconv.Itoa(i))};keys=append(keys,v.order...);case tsCollectionKind:keys=append(keys,(*tsCollection)(value.ref).order...);case tsClassKind:properties:=tsInstanceProperties((*tsClass)(value.ref).static);for _,name:=range properties.order{if descriptor:=properties.accessors[name];descriptor==nil||descriptor.enumerable{keys=append(keys,name)}};case tsObjectKind:object:=(*tsObject)(value.ref);for _,key:=range object.order{if descriptor:=object.descriptors[key];descriptor==nil||descriptor.enumerable{keys=append(keys,key)}};case tsInstanceKind:properties:=(*tsProperties)(value.ref);for _,name:=range properties.order{if descriptor:=properties.accessors[name];descriptor==nil||descriptor.enumerable{keys=append(keys,name)}};case tsArrayKind:v:=(*tsArray)(value.ref);for i:=0;i<v.length();i++{if !v.holes[i]{keys=append(keys,strconv.Itoa(i))}};for key:=range v.properties{if descriptor:=v.descriptors[key];descriptor==nil||descriptor.enumerable{keys=append(keys,key)}};case tsStringKind:for i:=range (*tsString)(value.ref).units{keys=append(keys,strconv.Itoa(i))};case tsECMAKind:keys=(*tsECMAObject)(value.ref).object.Keys();case tsNullKind,tsUndefinedKind:panic("Cannot enumerate null or undefined")};out:=&tsArray{};for _,key:=range tsOrderedKeys(keys){if tsIsSymbolKey(key){continue};out.values=append(out.values,tsStringKey(key))};return out}
func tsEnumerableOwnKeys(loop *tsLoop,value tsValue)*tsArray{keys:=tsObjectKeys(value);switch value.kind{case tsObjectKind,tsFunctionKind,tsInstanceKind,tsClassKind,tsArrayKind:for _,key:=range tsOwnKeys(value,true).values{descriptor:=tsOwnDescriptor(loop,value,tsPropertyKey(key));if !tsIsUndefined(descriptor)&&tsTruthy(tsGet(loop,descriptor,"enumerable")){keys.values=append(keys.values,key)}}};return keys}
func tsObjectSpread(target *tsObject,source tsValue){if tsNullish(source){return};for _,key:=range tsEnumerableOwnKeys(loop,source).values {target.set(tsPropertyKey(key),tsGet(source,key))}}
func tsObjectRest(source tsValue,excluded []tsValue)*tsObject {if tsNullish(source){panic("Cannot destructure null or undefined")};skip:=map[string]bool{};for _,key:=range excluded{skip[tsPropertyKey(key)]=true};out:=tsNewObject();for _,key:=range tsEnumerableOwnKeys(loop,source).values {if !skip[tsPropertyKey(key)] {out.set(tsPropertyKey(key),tsGet(source,key))}};return out}
func tsIteratorValue(iterator *tsIterator)tsValue{if iterator.next(){return iterator.value};return tsU}
func tsIteratorRest(iterator *tsIterator)*tsArray{out:=&tsArray{};for iterator.next(){out.values=append(out.values,iterator.value)};return out}
func tsArraySpread(target *tsArray,source tsValue){iterator:=tsIterate(source);for iterator.next(){target.appendItems(iterator.value)}}
func tsObjectBuiltin(name string,args []tsValue)tsValue{value:=tsArg(args,0);switch name{case "defineProperty","defineProperties","getOwnPropertyDescriptor","getOwnPropertyDescriptors","getOwnPropertyNames","create","setPrototypeOf","preventExtensions","isExtensible","seal","freeze","isSealed","isFrozen","is":return tsDescriptorBuiltin(loop,name,args);case "getPrototypeOf":if tsNullish(value){tsPropertyFailure("Cannot get prototype of null or undefined")};return tsPrototypeOf(value);case "getOwnPropertySymbols":return tsOwnKeys(value,true);case "keys":return tsObjectKeys(value);case "values","entries":out:=&tsArray{};for _,key:=range tsObjectKeys(value).values{item:=tsGet(value,key);if name=="entries"{item=&tsArray{values:[]tsValue{key,item}}};out.values=append(out.values,item)};return out;case "assign":target:=tsArg(args,0);for _,source:=range args[1:]{if tsNullish(source){continue};for _,key:=range tsEnumerableOwnKeys(loop,source).values{tsSet(target,key,tsGet(source,key))}};return target;case "hasOwn":key:=tsPropertyKey(tsArg(args,1));switch value.kind{case tsFunctionKind:return tsPrototypeOwn(value,key);case tsCollectionKind:_,ok:=(*tsCollection)(value.ref).properties[key];return ok;case tsTypedArrayKind:object:=(*tsTypedArray)(value.ref);if index,err:=strconv.Atoi(key);err==nil&&strconv.Itoa(index)==key&&index>=0&&index<object.length{return true};_,ok:=object.properties[key];return ok;case tsClassKind:return tsInstanceProperties((*tsClass)(value.ref).static).own[key];case tsObjectKind:object:=(*tsObject)(value.ref);_,ok:=object.values[key];return ok||object.descriptors[key]!=nil;case tsInstanceKind:return (*tsProperties)(value.ref).own[key];case tsArrayKind:object:=(*tsArray)(value.ref);if key=="length"{return true};index,err:=strconv.Atoi(key);if err==nil&&index>=0&&index<object.length()&&strconv.Itoa(index)==key{return !object.holes[index]};_,ok:=object.properties[key];return ok}};panic("Unsupported Object method")}
`
