package goemit

// Prototype storage is materialized only when observed or needed for dynamic
// dispatch. Once protects runtime initialization, not user-written mutations.
const prototypeRuntime = `
func tsInstanceWrite(loop *tsLoop,receiver tsValue,name string,value tsValue)tsValue{var properties *tsProperties;if receiver.kind==tsClassKind{properties=tsInstanceProperties((*tsClass)(receiver.ref).static)}else{properties=tsInstanceProperties(receiver)};if properties.nonExtensible&&!properties.own[name]{tsPropertyFailure("Cannot add property to non-extensible instance")};if descriptor:=properties.accessors[name];descriptor!=nil&&descriptor.accessor{if tsIsUndefined(descriptor.setter){tsPropertyFailure("Property has no setter")};tsCallReceiver(loop,descriptor.setter,receiver,value);return value};if descriptor:=properties.accessors[name];descriptor!=nil&&!descriptor.writable{tsPropertyFailure("Cannot write read-only property")};if !properties.own[name]&&properties.class!=nil&&properties.class.dynamic{for cursor:=tsPrototypeOf(receiver);!tsNullish(cursor);cursor=tsPrototypeOf(cursor){if cursor.kind==tsObjectKind{object:=(*tsObject)(cursor.ref);if descriptor:=object.descriptors[name];descriptor!=nil{if descriptor.accessor{if tsIsUndefined(descriptor.setter){tsPropertyFailure("Property has no setter")};tsCallReceiver(loop,descriptor.setter,receiver,value);return value};if !descriptor.writable{tsPropertyFailure("Cannot write read-only inherited property")};break};if _,ok:=object.values[name];ok{break}}}};return properties.set(name,value)}
var tsIntrinsics struct {sync.Once;object *tsObject;function *tsFunction;objectConstructor,functionConstructor *tsFunction}
func tsInitPrototypes(){tsIntrinsics.Do(func(){
 object:=tsNewObject();object.prototype=tsNull;tsIntrinsics.object=object
 function:=tsFunc(func(args ...tsValue)tsValue{return tsU});tsIntrinsics.function=function
 objectConstructor:=tsFunc(func(args ...tsValue)tsValue{value:=tsArg(args,0);if tsNullish(value){return tsObjectValue(tsNewObject())};if !tsIsPrimitiveValue(value){return value};out:=tsNewObject();out.set("value",value);return tsObjectValue(out)})
 objectConstructor.name="Object";objectConstructor.length=1;objectConstructor.constructible=true;objectConstructor.properties=tsNewObject();objectConstructor.properties.set("prototype",tsObjectValue(object));objectConstructor.properties.descriptors=map[string]*tsDescriptor{"prototype":{}};tsIntrinsics.objectConstructor=objectConstructor
 functionConstructor:=tsFunc(func(args ...tsValue)tsValue{tsPropertyFailure("Dynamic Function compilation is not supported");return tsU});functionConstructor.name="Function";functionConstructor.length=1;functionConstructor.constructible=true;functionConstructor.properties=tsNewObject();functionConstructor.properties.set("prototype",tsFunctionValue(function));functionConstructor.properties.descriptors=map[string]*tsDescriptor{"prototype":{}};tsIntrinsics.functionConstructor=functionConstructor
 object.set("constructor",tsFunctionValue(objectConstructor))
 object.order=append(object.order,"__proto__");object.descriptors=map[string]*tsDescriptor{"__proto__":{accessor:true,configurable:true,getter:tsNativeMethod(func(loop *tsLoop,receiver tsValue,args ...tsValue)tsValue{return tsPrototypeOf(receiver)}),setter:tsNativeMethod(func(loop *tsLoop,receiver tsValue,args ...tsValue)tsValue{prototype:=tsArg(args,0);if tsIsPrimitiveValue(prototype)&&prototype.kind!=tsNullKind{return tsU};tsSetPrototype(receiver,prototype);return tsU})}}
 object.set("hasOwnProperty",tsNativeMethod(func(loop *tsLoop,receiver tsValue,args ...tsValue)tsValue{return tsObjectBuiltin("hasOwn",[]tsValue{receiver,tsArg(args,0)})}))
 object.set("propertyIsEnumerable",tsNamedNativeMethod("propertyIsEnumerable",1,func(loop *tsLoop,receiver tsValue,args ...tsValue)tsValue{return tsBooleanValue(tsArrayPropertyEnumerable(loop,receiver,tsArg(args,0)))}))
 object.set("isPrototypeOf",tsNativeMethod(func(loop *tsLoop,receiver tsValue,args ...tsValue)tsValue{if tsNullish(receiver){tsPropertyFailure("Invalid prototype receiver")};return tsBooleanValue(tsPrototypeContains(tsArg(args,0),receiver))}))
 object.set("valueOf",tsNativeMethod(func(loop *tsLoop,receiver tsValue,args ...tsValue)tsValue{if tsNullish(receiver){tsPropertyFailure("Invalid object receiver")};return receiver}))
 object.set("toString",tsNativeMethod(func(loop *tsLoop,receiver tsValue,args ...tsValue)tsValue{return tsObjectTag(loop,receiver)}))
 for _,name:=range object.order{if object.descriptors==nil{object.descriptors=map[string]*tsDescriptor{}};if object.descriptors[name]==nil{object.descriptors[name]=&tsDescriptor{writable:true,configurable:true}}}
 function.properties=tsNewObject();function.properties.set("constructor",tsFunctionValue(functionConstructor))
 function.properties.set("call",tsNamedNativeMethod("call",1,func(loop *tsLoop,receiver tsValue,args ...tsValue)tsValue{return tsCallReceiver(loop,receiver,tsArg(args,0),tsRestArgs(args,1).values...)}))
 function.properties.set("apply",tsNamedNativeMethod("apply",2,func(loop *tsLoop,receiver tsValue,args ...tsValue)tsValue{values:=[]tsValue{};source:=tsArg(args,1);if !tsNullish(source){iterator:=tsArrayLikeIterator(source);for iterator.next(loop){values=append(values,iterator.value)}};return tsCallReceiver(loop,receiver,tsArg(args,0),values...)}))
 function.properties.set("bind",tsNamedNativeMethod("bind",1,func(loop *tsLoop,target tsValue,args ...tsValue)tsValue{if target.kind!=tsFunctionKind{tsPropertyFailure("bind receiver is not callable")};receiver:=tsArg(args,0);prefix:=append([]tsValue{},tsRestArgs(args,1).values...);bound:=tsFunc(func(loop *tsLoop,args ...tsValue)tsValue{values:=append(append([]tsValue{},prefix...),args...);return tsCallReceiver(loop,target,receiver,values...)});bound.boundTarget=target;bound.boundReceiver=receiver;bound.boundArgs=prefix;bound.internalPrototype=tsPrototypeOf(target);return tsFunctionValue(bound)}))
 function.properties.descriptors=map[string]*tsDescriptor{};for _,name:=range function.properties.order{function.properties.descriptors[name]=&tsDescriptor{writable:true,configurable:true}}
 key:=tsPropertyKey(tsWellKnownSymbol("hasInstance"));function.properties.set(key,tsNamedNativeMethod("[Symbol.hasInstance]",1,func(loop *tsLoop,receiver tsValue,args ...tsValue)tsValue{if receiver.kind!=tsFunctionKind&&receiver.kind!=tsClassKind{return tsBooleanValue(false)};return tsBooleanValue(tsOrdinaryInstanceOf(tsArg(args,0),receiver))}));function.properties.descriptors[key]=&tsDescriptor{}
 })}
func tsObjectLiteralPrototype(object *tsObject,value tsValue){if value.kind==tsNullKind||!tsIsPrimitiveValue(value){object.prototype=value}}
func tsObjectPrototype()tsValue{tsInitPrototypes();return tsObjectValue(tsIntrinsics.object)}
func tsObjectConstructor()tsValue{tsInitPrototypes();return tsFunctionValue(tsIntrinsics.objectConstructor)}
func tsFunctionConstructor()tsValue{tsInitPrototypes();return tsFunctionValue(tsIntrinsics.functionConstructor)}
func(f *tsFunction)readProperties()*tsObject{if object:=f.metadataRef.Load();object!=nil{return object};return f.properties}
func(f *tsFunction)metadata()*tsObject{f.metadataOnce.Do(func(){object:=tsNewObject();object.descriptors=map[string]*tsDescriptor{};if previous:=f.properties;previous!=nil{object.order=append(object.order,previous.order...);for name,value:=range previous.values{object.values[name]=value};for name,description:=range previous.descriptors{object.descriptors[name]=description}};for _,name:=range []string{"name","length"}{if !tsOwnObjectProperty(object,name){value:=tsNumberValue(float64(f.length));if name=="name"{value=tsStringReference(tsStringUTF8(f.name))};object.set(name,value);object.descriptors[name]=&tsDescriptor{configurable:true}}};if (f.constructible||f.generator)&&!tsOwnObjectProperty(object,"prototype"){object.set("prototype",tsFunctionPrototype(tsFunctionValue(f)));object.descriptors["prototype"]=&tsDescriptor{writable:true}};f.metadataRef.Store(object)});return f.metadataRef.Load()}

func tsFunctionWrite(loop *tsLoop,receiver tsValue,name string,value tsValue)tsValue{function:=(*tsFunction)(receiver.ref);object:=function.metadata();if name=="prototype"&&(function.constructible||function.generator)&&!tsOwnObjectProperty(object,name){object.set(name,tsFunctionPrototype(receiver));object.descriptors[name]=&tsDescriptor{writable:true}};if descriptor:=object.descriptors[name];descriptor!=nil&&descriptor.accessor{if tsIsUndefined(descriptor.setter){tsPropertyFailure("Property has no setter")};tsCallReceiver(loop,descriptor.setter,receiver,value);return value};return tsObjectWrite(loop,tsObjectValue(object),name,value)}
func tsFunctionPrototype(value tsValue)tsValue{function:=(*tsFunction)(value.ref);if !function.constructible&&!function.generator{return tsU};function.prototypeOnce.Do(func(){object:=tsNewObject();if function.generator{object.prototype=tsGeneratorPrototype(function.asyncGeneratorFunction);function.prototype=tsObjectValue(object);return};object.set("constructor",value);object.descriptors=map[string]*tsDescriptor{"constructor":{writable:true,configurable:true}};function.prototype=tsObjectValue(object)});return function.prototype}
func tsClassPrototype(class *tsClass)tsValue{if class.builtin=="Array"{return tsArrayPrototype(loop)};if class.builtin!=""&&class.nativePrototype!=nil{return tsObjectValue(class.nativePrototype)};class.prototypeOnce.Do(func(){if class.prototypeFactory!=nil{class.nativePrototype=class.prototypeFactory()}else{class.nativePrototype=tsNewObject();class.nativePrototype.set("constructor",tsClassValue(class))}});return tsObjectValue(class.nativePrototype)}
func tsPrototypeOf(value tsValue)tsValue{switch value.kind{case tsArrayKind:array:=(*tsArray)(value.ref);if !tsIsUndefined(array.prototype){return array.prototype};return tsArrayPrototype(loop);
 case tsIteratorKind:iterator:=(*tsIterator)(value.ref);if !tsIsUndefined(iterator.prototype){return iterator.prototype};tsInitGenerators();return tsObjectValue(tsGeneratorIntrinsics.iteratorPrototype)
 case tsSymbolKind:tsInitSymbols();return tsObjectValue(tsSymbols.prototype)
 case tsErrorKind:return tsErrorPrototype((*tsRuntimeError)(value.ref).name)
 case tsObjectKind:object:=(*tsObject)(value.ref);if !tsIsUndefined(object.prototype){return object.prototype};if object.nativeClass!=nil{return tsClassPrototype(object.nativeClass)};return tsObjectPrototype()
 case tsFunctionKind:function:=(*tsFunction)(value.ref);if !tsIsUndefined(function.internalPrototype){return function.internalPrototype};if function.generator{return tsGeneratorFunctionPrototype(function.asyncGeneratorFunction)};tsInitPrototypes();if function==tsIntrinsics.function{return tsObjectPrototype()};return tsFunctionValue(tsIntrinsics.function)
 case tsInstanceKind:p:=(*tsProperties)(value.ref);if !tsIsUndefined(p.dynamicPrototype){return p.dynamicPrototype};if p.class!=nil{return tsClassPrototype(p.class)};return tsObjectPrototype()
 case tsClassKind:class:=(*tsClass)(value.ref);if !tsIsUndefined(class.baseConstructor){return class.baseConstructor};if class.parent!=nil{return tsClassValue(class.parent)};tsInitPrototypes();return tsFunctionValue(tsIntrinsics.function)
 };return tsNull}
func tsPrototypeContains(value,prototype tsValue)bool{if tsIsPrimitiveValue(value){return false};for cursor:=tsPrototypeOf(value);!tsNullish(cursor);cursor=tsPrototypeOf(cursor){if tsStrictEqual(cursor,prototype){return true}};return false}
func tsPrototypeLookup(loop *tsLoop,receiver,prototype tsValue,name string)tsValue{
 for cursor:=prototype;!tsNullish(cursor);cursor=tsPrototypeOf(cursor){switch cursor.kind{case tsArrayKind:array:=(*tsArray)(cursor.ref);if value,ok:=array.properties[name];ok{return value};case tsObjectKind:object:=(*tsObject)(cursor.ref);if descriptor:=object.descriptors[name];descriptor!=nil&&descriptor.accessor{if tsIsUndefined(descriptor.getter){return tsU};return tsCallReceiver(loop,descriptor.getter,receiver)};if value,ok:=object.values[name];ok{return value}
 case tsClassKind:class:=(*tsClass)(cursor.ref);properties:=tsInstanceProperties(class.static);if descriptor:=properties.accessors[name];descriptor!=nil&&descriptor.accessor{if tsIsUndefined(descriptor.getter){return tsU};return tsCallReceiver(loop,descriptor.getter,receiver)};if properties.own[name]{return properties.get(name)}
 case tsFunctionKind:function:=(*tsFunction)(cursor.ref);if object:=function.readProperties();object!=nil{if descriptor:=object.descriptors[name];descriptor!=nil&&descriptor.accessor{if tsIsUndefined(descriptor.getter){return tsU};return tsCallReceiver(loop,descriptor.getter,receiver)};if value,ok:=object.values[name];ok{return value}};if function.metadataRef.Load()==nil{if name=="name"{return tsStringReference(tsStringUTF8(function.name))};if name=="length"{return tsNumberValue(float64(function.length))};if name=="prototype"&&(function.constructible||function.generator){return tsFunctionPrototype(cursor)}}}}

 return tsU
}
func tsTrySetPrototype(value,prototype tsValue)bool{
 if tsSameValue(tsPrototypeOf(value),prototype){return true};if tsSameValue(prototype,value)||tsPrototypeContains(prototype,value){return false}
 switch value.kind{case tsObjectKind:object:=(*tsObject)(value.ref);if object.nonExtensible{return false};object.prototype=prototype
 case tsFunctionKind:function:=(*tsFunction)(value.ref);if function.metadata().nonExtensible{return false};function.internalPrototype=prototype
 case tsInstanceKind:properties:=(*tsProperties)(value.ref);if properties.nonExtensible{return false};properties.dynamicPrototype=prototype
 case tsArrayKind:(*tsArray)(value.ref).prototype=prototype
 default:return false};return true
}
func tsSetPrototype(value,prototype tsValue)tsValue{if tsNullish(value){tsPropertyFailure("Cannot set prototype of null or undefined")};if prototype.kind!=tsNullKind&&tsIsPrimitiveValue(prototype){tsPropertyFailure("Prototype must be an object or null")};if tsIsPrimitiveValue(value){return value};if !tsTrySetPrototype(value,prototype){tsPropertyFailure("Cannot change object prototype")};return value}
func tsClassRead(loop *tsLoop,value tsValue,name string)tsValue{class:=(*tsClass)(value.ref);if !class.dynamic{return tsInstanceProperties(class.static).get(name)};for at:=class;at!=nil;at=at.parent{properties:=tsInstanceProperties(at.static);if descriptor:=properties.accessors[name];descriptor!=nil&&descriptor.accessor{if tsIsUndefined(descriptor.getter){return tsU};return tsCallReceiver(loop,descriptor.getter,value)};if properties.own[name]{return properties.get(name)}};return tsPrototypeLookup(loop,value,tsPrototypeOf(tsClassValue(class)),name)}
func tsInstanceRead(loop *tsLoop,value tsValue,name string)tsValue{p:=(*tsProperties)(value.ref);if descriptor:=p.accessors[name];descriptor!=nil&&descriptor.accessor{if tsIsUndefined(descriptor.getter){return tsU};return tsCallReceiver(loop,descriptor.getter,value)};if p.class==nil||!p.class.dynamic{return p.get(name)};if property,ok:=p.declared[name];ok&&p.own[name]{return property.readField()};if item,ok:=p.extra[name];ok{return item};return tsPrototypeLookup(loop,value,tsPrototypeOf(value),name)}
`

const prototypeMembershipRuntime = `
func tsPrototypeOwn(value tsValue,name string)bool{switch value.kind{case tsObjectKind:return tsOwnObjectProperty((*tsObject)(value.ref),name);case tsFunctionKind:function:=(*tsFunction)(value.ref);if object:=function.metadataRef.Load();object!=nil{return tsOwnObjectProperty(object,name)};return name=="name"||name=="length"||name=="prototype"&&(function.constructible||function.generator)||function.readProperties()!=nil&&tsOwnObjectProperty(function.readProperties(),name);case tsInstanceKind:return (*tsProperties)(value.ref).own[name];case tsClassKind:return name=="prototype"||tsInstanceProperties((*tsClass)(value.ref).static).own[name]};return false}
func tsPrototypeHas(value tsValue,name string)bool{for cursor:=value;!tsNullish(cursor);cursor=tsPrototypeOf(cursor){if tsPrototypeOwn(cursor,name){return true}};return false}
func tsPrototypeForIn(value tsValue)*tsArray{out:=&tsArray{};seen:=map[string]bool{};for cursor:=value;!tsNullish(cursor);cursor=tsPrototypeOf(cursor){names:=[]string{};switch cursor.kind{case tsObjectKind:names=(*tsObject)(cursor.ref).order;case tsFunctionKind:names=[]string{"name","length"};function:=(*tsFunction)(cursor.ref);if function.constructible{names=append(names,"prototype")};if object:=function.readProperties();object!=nil{names=append(names,object.order...)};case tsInstanceKind:names=(*tsProperties)(cursor.ref).order;default:for _,key:=range tsObjectKeys(cursor).values{names=append(names,tsPropertyKey(key))}}
 enumerable:=map[string]bool{};for _,key:=range tsObjectKeys(cursor).values{enumerable[tsPropertyKey(key)]=true};for _,name:=range tsOrderedKeys(names){if seen[name]||tsIsSymbolKey(name){continue};seen[name]=true;if enumerable[name]{out.values=append(out.values,tsStringReference(tsStringKey(name)))}}};return out}
`
