package goemit

const reflectRuntime = `
func tsReflectDescriptorKind(value tsValue)bool{switch value.kind{case tsObjectKind,tsFunctionKind,tsInstanceKind,tsClassKind,tsErrorKind:return true};return false}
func tsReflectGet(loop *tsLoop,target tsValue,name string,receiver tsValue)tsValue{
 for cursor:=target;!tsNullish(cursor);cursor=tsPrototypeOf(cursor){if !tsReflectDescriptorKind(cursor){return tsGet(loop,cursor,tsKeyValue(name))};description:=tsOwnDescriptor(loop,cursor,name);if tsIsUndefined(description){continue};if tsHas(description,tsStringReference(tsStringUTF8("get"))){getter:=tsGet(loop,description,"get");if tsIsUndefined(getter){return tsU};return tsCallReceiver(loop,getter,receiver)};return tsGet(loop,description,"value")};return tsU
}
func tsReflectSet(loop *tsLoop,target tsValue,name string,value,receiver tsValue)bool{
 for cursor:=target;!tsNullish(cursor);cursor=tsPrototypeOf(cursor){if !tsReflectDescriptorKind(cursor){tsSet(loop,target,tsKeyValue(name),value);return true};description:=tsOwnDescriptor(loop,cursor,name);if tsIsUndefined(description){continue};if tsHas(description,tsStringReference(tsStringUTF8("set"))){setter:=tsGet(loop,description,"set");if tsIsUndefined(setter){return false};tsCallReceiver(loop,setter,receiver,value);return true};if !tsTruthy(tsGet(loop,description,"writable")){return false};break}
 if tsIsPrimitiveValue(receiver){return false};if !tsReflectDescriptorKind(receiver){tsSet(loop,receiver,tsKeyValue(name),value);return true};own:=tsOwnDescriptor(loop,receiver,name);description:=tsNewObject();description.set("value",value)
 if !tsIsUndefined(own){if tsHas(own,tsStringReference(tsStringUTF8("set")))||!tsTruthy(tsGet(loop,own,"writable")){return false}}else{description.set("writable",tsBooleanValue(true));description.set("enumerable",tsBooleanValue(true));description.set("configurable",tsBooleanValue(true))}
 return tsTryDefineProperty(loop,receiver,name,tsObjectValue(description))
}
var tsReflectNamespace struct{sync.Once;object *tsObject}
func tsReflectModule()tsValue{tsReflectNamespace.Do(func(){object:=tsNewObject();object.descriptors=map[string]*tsDescriptor{}
 for _,name:=range []string{"ownKeys","deleteProperty","get","set","has","getOwnPropertyDescriptor","defineProperty","getPrototypeOf","setPrototypeOf","isExtensible","preventExtensions","apply","construct"}{operation:=name;arity:=2;if name=="ownKeys"||name=="getPrototypeOf"||name=="isExtensible"||name=="preventExtensions"{arity=1};if name=="set"||name=="defineProperty"||name=="apply"{arity=3};object.set(name,tsNamedNativeMethod(name,arity,func(loop *tsLoop,receiver tsValue,args ...tsValue)tsValue{
  target:=tsArg(args,0);if tsIsPrimitiveValue(target){tsPropertyFailure("Reflect requires an object")}
  switch operation{case "ownKeys":return tsArrayValue(tsOwnKeys(target,false));case "deleteProperty":return tsBooleanValue(tsDelete(loop,target,tsArg(args,1),false));case "get":receiver:=target;if len(args)>2{receiver=args[2]};return tsReflectGet(loop,target,tsPropertyKey(tsArg(args,1)),receiver);case "set":receiver:=target;if len(args)>3{receiver=args[3]};return tsBooleanValue(tsReflectSet(loop,target,tsPropertyKey(tsArg(args,1)),tsArg(args,2),receiver));case "has":return tsBooleanValue(tsHas(target,tsArg(args,1)));case "getOwnPropertyDescriptor":return tsOwnDescriptor(loop,target,tsPropertyKey(tsArg(args,1)));case "getPrototypeOf":return tsPrototypeOf(target);case "isExtensible":return tsDescriptorBuiltin(loop,"isExtensible",args);case "preventExtensions":tsDescriptorBuiltin(loop,"preventExtensions",args);return tsBooleanValue(true);case "setPrototypeOf":prototype:=tsArg(args,1);if prototype.kind!=tsNullKind&&tsIsPrimitiveValue(prototype){tsPropertyFailure("Prototype must be an object or null")};return tsBooleanValue(tsTrySetPrototype(target,prototype));case "defineProperty":return tsBooleanValue(tsTryDefineProperty(loop,target,tsPropertyKey(tsArg(args,1)),tsArg(args,2)));case "apply","construct":if operation=="construct"{if !tsIsConstructor(target){tsPropertyFailure("Value is not a constructor")};if len(args)>2&&!tsIsConstructor(args[2]){tsPropertyFailure("newTarget is not a constructor")}};list:=tsArg(args,1);if operation=="apply"{list=tsArg(args,2)};iterator:=tsArrayLikeIterator(list);values:=[]tsValue{};for iterator.next(loop){values=append(values,iterator.value)};if operation=="apply"{return tsCallReceiver(loop,target,tsArg(args,1),values...)};return tsConstruct(target,values...)};return tsU
 }));object.descriptors[name]=&tsDescriptor{writable:true,configurable:true}}
 tsReflectNamespace.object=object});return tsObjectValue(tsReflectNamespace.object)}
`
