package goemit

// The ECMAScript engine supplies RegExp and ECMAScript numeric conversions.
// No application source or eval/Function input is compiled or executed here.
const RegexRuntime = `
func tsEngine(loop *tsLoop)*goja.Runtime {if loop.ecma==nil {loop.ecma=goja.New()};return loop.ecma}
type tsRegExp struct {object *goja.Object}
type tsECMAObject struct {object *goja.Object}
// Goja owns a separate Value API and requires host values at this boundary.
func tsToECMA(value tsValue)goja.Value{if tsIsNumeric(value){return tsEngine().ToValue(tsNumber(value))};switch value.kind{case tsBigIntKind:return tsEngine().ToValue(new(big.Int).Set((*big.Int)(value.ref)));case tsUndefinedKind:return goja.Undefined();case tsNullKind:return goja.Null();case tsNumberKind:return tsEngine().ToValue(value.number);case tsBooleanKind:return tsEngine().ToValue(value.number!=0);case tsStringKind:return goja.StringFromUTF16((*tsString)(value.ref).units);case tsRegExpKind:return (*tsRegExp)(value.ref).object;case tsECMAKind:return (*tsECMAObject)(value.ref).object;case tsObjectKind:v:=(*tsObject)(value.ref);object:=tsEngine().NewObject();for _,key:=range v.order{if err:=object.Set(key,tsToECMA(v.values[key]));err!=nil{tsECMAFailure(err)}};return object;case tsArrayKind:v:=(*tsArray)(value.ref);values:=make([]any,v.length());for i:=0;i<v.length();i++{item:=v.at(i);values[i]=tsToECMA(item)};return tsEngine().NewArray(values...);case tsFunctionKind:return tsEngine().ToValue(func(call goja.FunctionCall)goja.Value{args:=make([]tsValue,len(call.Arguments));for i,arg:=range call.Arguments{args[i]=tsFromECMA(arg)};return tsToECMA(tsCall(value,args...))});default:panic("Unsupported JavaScript value at Goja boundary")}}
func tsFromECMA(value goja.Value)tsValue{if goja.IsUndefined(value){return tsU};if goja.IsNull(value){return tsNull};if text,ok:=value.(goja.String);ok{units:=make([]uint16,text.Length());for i:=range units{units[i]=text.CharAt(i)};return tsStringReference(tsStringUnits(units))};if object,ok:=value.(*goja.Object);ok{if object.ClassName()=="RegExp"{return tsRegExpValue(&tsRegExp{object})};if object.ClassName()=="Array"{length:=int(object.Get("length").ToInteger());array:=&tsArray{values:make([]tsValue,length)};for i:=range array.values{array.values[i]=tsFromECMA(object.Get(strconv.Itoa(i)))};for _,key:=range object.Keys(){if index,err:=strconv.Atoi(key);err!=nil||index<0||index>=length||strconv.Itoa(index)!=key{if array.properties==nil{array.properties=map[string]tsValue{}};array.properties[key]=tsFromECMA(object.Get(key))}};return tsArrayValue(array)};return tsECMAValue(&tsECMAObject{object})};switch v:=value.Export().(type){case *big.Int:return tsBigIntValue(new(big.Int).Set(v));case int64:return tsNumberValue(float64(v));case int32:return tsNumberValue(float64(v));case int:return tsNumberValue(float64(v));case float64:return tsNumberValue(v);case bool:return tsBooleanValue(v);default:panic("Unsupported Goja primitive")}}
func tsECMAFailure(err error) {if exception,ok:=err.(*goja.Exception);ok {panic(tsThrown{tsFromECMA(exception.Value())})};panic(err.Error())}
func tsNewRegExp(args ...tsValue) tsValue {arguments:=make([]goja.Value,len(args));for i,value:=range args {arguments[i]=tsToECMA(value)};constructor,_:=goja.AssertConstructor(tsEngine().Get("RegExp"));object,err:=constructor(nil,arguments...);if err!=nil {tsECMAFailure(err)};return &tsRegExp{object}}
func tsECMAGet(object *goja.Object,key tsValue) tsValue {name:=tsText(key);value:=object.Get(name);if call,ok:=goja.AssertFunction(value);ok {return tsFunc(func(args ...tsValue)tsValue{arguments:=make([]goja.Value,len(args));for i,arg:=range args {arguments[i]=tsToECMA(arg)};result,err:=call(object,arguments...);if err!=nil {tsECMAFailure(err)};return tsFromECMA(result)})};return tsFromECMA(value)}
func tsECMASet(object *goja.Object,key,value tsValue) tsValue {if err:=object.Set(tsText(key),tsToECMA(value));err!=nil {tsECMAFailure(err)};return value}
func tsRegexString(text *tsString,name string,args []tsValue) tsValue {prototype:=tsEngine().Get("String").ToObject(tsEngine()).Get("prototype").ToObject(tsEngine());method,ok:=goja.AssertFunction(prototype.Get(name));if !ok {panic("ECMAScript String method unavailable: "+name)};arguments:=make([]goja.Value,len(args));for i,arg:=range args {arguments[i]=tsToECMA(arg)};result,err:=method(goja.StringFromUTF16(text.units),arguments...);if err!=nil {tsECMAFailure(err)};return tsFromECMA(result)}
`
